export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const GET_INGREDIENTS = 'GET_INGREDIENTS';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENT_FAILED = 'FETCH_INGREDIENT_FAILED';

export const POST_ORDER_SUCCESS = 'POST_ORDER_SUCCESS';
export const POST_ORDER_FAIL = 'POST_ORDER_FAIL';
export const POST_ORDER_START = 'POST_ORDER_START';
export const POST_ORDER_INTEND = 'POST_ORDER_INTEND';
export const PURCHASE_INIT = 'PURCHASE_INIT';


export const FETCH_ORDERS_INTEND = 'FETCH_ORDERS_INTEND';
export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOG_OUT = 'AUTH_LOG_OUT';
export const AUTH_INITIATE_LOG_OUT = 'AUTH_INITIATE_LOG_OUT';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_REAUTHORIZE = 'AUTH_REAUTHORIZE';
export const SET_AUTH_REDIRECT="SET_AUTH_REDIRECT";
export const AUTH_INITIATE_AUTH="AUTH_INITIATE_AUTH";

